params:
  seed: 42
  env: {}
  algo:
    name: a2c_discrete
  model:
    name: discrete_a2c
  network:
    name: actor_critic
    separate: True
    space:
      discrete: {}
    mlp:
      units: [1024, 512]
      activation: relu
      d2rl: False
      initializer:
        name: default
      regularizer:
        name: None
  load_checkpoint: False
  load_path: ''
  config:
    name: skillmimic_hlc_isaaclab
    env_name: rlgpu
    device: 'cuda:0'
    device_name: 'cuda:0'
    multi_gpu: False
    ppo: True
    mixed_precision: False
    normalize_input: True
    normalize_value: True
    value_bootstrap: True
    num_actors: -1
    reward_shaper:
      scale_value: 1.0
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 2.0e-5
    lr_schedule: constant
    max_epochs: 6000
    save_best_after: 10
    save_frequency: 50
    grad_norm: 1.0
    entropy_coef: 0.0
    truncate_grads: False
    e_clip: 0.2
    horizon_length: 32
    minibatch_size: 16384
    mini_epochs: 6
    critic_coef: 5
    clip_value: False
    seq_length: 4
    bounds_loss_coef: 10
